name: Build and Package Plugin

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Read plugin metadata (id, version)
        run: |
          echo "ID=$(node -p "require('./manifest.json').id")" >> "$GITHUB_ENV"
          echo "VERSION=$(node -p "require('./manifest.json').version")" >> "$GITHUB_ENV"

      - name: Package release files
        run: |
          mkdir -p dist
          zip -j "dist/${ID}-${VERSION}.zip" manifest.json main.js styles.css || true
          # Fallback: if styles.css does not exist, create a zip with the required files only
          if [ ! -s "dist/${ID}-${VERSION}.zip" ]; then
            zip -j "dist/${ID}-${VERSION}.zip" manifest.json main.js
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ID }}-${{ env.VERSION }}
          path: dist/*.zip
          if-no-files-found: error
          retention-days: 14

